### ISSUE TITLE
db hints

### ISSUE THREAD

**Issue by vitaly-t** [lakesare/memcode#1]
to avoid pg-promise api misuse, read these:

* https://coderwall.com/p/irklcq/pg-promise-and-case-sensitivity-in-column-names
* http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings

**Comment by lakesare** [comment]
@vitaly-t, ironically I'm the author of the first article you referenced :-D

**Comment by vitaly-t** [comment]
@lakesare ha, really? 👍 😄

**Comment by lakesare** [comment]
@vitaly-t, yes. But it's very nice how you care about people using your library properly.
