### ISSUE TITLE
create duplicates of existing flashcards

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#10]
Can you provide a short cut for creating a duplicate of an existing flashcard?

**Comment by lakesare** [comment]
Do you do it frequently enough for simple copy/paste to be a hassle?
If your issue is some colors/formatting getting lost on copypaste then that should be a #todo instead (I remember formatting gets lost on copypaste, and I know it's fixable).

**Comment by lakesare** [comment]
Closing this as we implemented course duplication. You're free to reopen the issue if you need flashcard duplication in particular.
