### ISSUE TITLE
Import a flashcard from another course

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#11]
Is this possible? 

And on a related note, how about remixing an existing course by adding my own flashcards to it?

**Comment by lakesare** [comment]
It is possible to export multiple flashcards from one course of yours to another by clicking on the number next to the said flashcard:

![image](https://user-images.githubusercontent.com/7578559/75593196-7bf01e80-5a7c-11ea-981f-562753a25130.png)

It's not possible to export flashcards from the course of someone else though, I think that's not frequently needed.

**Comment by kgashok** [comment]
Please consider enabling "export" to spreadsheet for someone else's course. This way, it can be exported and imported by the user and remixed.

**Comment by kgashok** [comment]
> It is possible to export multiple flashcards from one course of yours to another by clicking on the number next to the said flashcard:

> > Additionally, an option to "Select All" flashcards may be provided as a convenience for export.

**Comment by lakesare** [comment]
@kgashok, I decided I'm going to implement course duplication (and then the user can delete the flashcards they don't need). I think that's going to be cleaner for UI than adding the duplicate button next to each flashcard.

**Comment by lakesare** [comment]
Implemented the course duplication functionality ✅

You can go to someone else's course, and click 'Duplicate':

![image](https://user-images.githubusercontent.com/7578559/76526812-f44cdb80-648f-11ea-8c8b-fe18aa63af6c.png)

(Refresh your cache if you don't see it).

Tell me if it works well for you!

**Comment by kgashok** [comment]
Yes, works perfectly. 👏
