### ISSUE TITLE
Add hotkey for inserting KaTeX formulas

### ISSUE THREAD

**Issue by daniel-eder** [lakesare/memcode#116]
To make creating math-heavy courses that much easier :)

**Comment by lakesare** [comment]
Good idea, thinking of a shortcut.
`Shift + cmd + f` opens my profile on mac:
![image](https://user-images.githubusercontent.com/7578559/113577288-716a6600-963a-11eb-9b48-6baadbd5191a.png)

![image](https://user-images.githubusercontent.com/7578559/113577323-7e875500-963a-11eb-8bb4-dd2fc97e4150.png)
