### ISSUE TITLE
Add support for the MathQuill editor

### ISSUE THREAD

**Issue by daniel-eder** [lakesare/memcode#118]
https://github.com/c-w/mathquill4quill
As suggested in https://github.com/lakesare/memcode/issues/115#issuecomment-813381008

- [x] Add MathQuill dependency
- [x] Add basic mathquill4quill support to quill react editor
- [ ] Add proper css loading via webpack https://webpack.js.org/loaders/css-loader/
- [x] Style to fit memcode

**Comment by lakesare** [comment]
**mathquill4quill** seems really nice, but they can't render some advanced formulas.
So using **mathquill4quill** would disable us from using, e.g., `mathfrak` (see https://github.com/c-w/mathquill4quill/issues/70).

Update: `mathfrak` still doesn't work in **mathquill4quill** in June 2022.
