### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 after saving a card

### ISSUE THREAD

**Issue by initBasti** [lakesare/memcode#123]
Hello,

just wanted to report a small bug, that I encountered while saving a card. The card seems to be saved just fine but the warning seems to be created during the process. Here is a screenshot of the problem, I hope it helps :).
[Screenshot](https://imgur.com/a/RV8ZLhT)

Greetings,
Sebastian

**Comment by lakesare** [comment]
Hi! Please refresh your browser with CMD+SHIFT+R, this should help.
We should implement a better cache busting solution 😓

**Comment by initBasti** [comment]
Hi @lakesare 
Hmm, the card disappeared after the refresh. But after adding it again it works now.
Thanks and greetings,
Sebastian
