### ISSUE TITLE
Duplicate cards or create card templates.

### ISSUE THREAD

**Issue by peepincreepin** [lakesare/memcode#125]
I create a lot of cards in the sam format. It would be really useful if we could create personal templates, or if we could easily duplicate cards, to make this process easier.

**Comment by lakesare** [comment]
Duplication is something that I've considered - however, as a quick solution, - try pressing "CMD + Z" in the new-flashcard input right after you saved the previous flashcard.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/7578559/129438154-150a8509-5ca5-45ca-9420-5a5ddff1b078.png">

**Comment by piotrvidal** [comment]
How should this functionality look like?

UI proposal:
![duplicate_ui_example](https://user-images.githubusercontent.com/98980760/155551885-7ebc7120-ce92-497f-8c33-63e43283ab73.png)

Or maybe on the other side? Or maybe next to "New Flashcard", similar format, but "Duplicate Previous Flashcard" (although that's too many words).

**Comment by lakesare** [comment]
Your suggestion looks great to me. I'd move "Duplicate" above "Export".

There are multiple UI options I considered:
1. "only on the left"
2. "on the left and on the right"
3. "only on the left, but with a 3-dot submenu" (we need other flashcard-specific functionality too, e.g. "Switch Type of the flashcard", and it will be hard to fit this phrasing into the current UI).

For now I'd suggest the "on the left" option, like in your screenshot. After we deploy it, it will be much more clear what UI is the best.

**Comment by peepincreepin** [comment]
This looks great; thank you! :)

**Comment by lakesare** [comment]
This is done, implemented the flashcard duplication ([twitter.com/memcodeapp/status/1544351377165615111](https://twitter.com/memcodeapp/status/1544351377165615111))!

<img width="213" alt="image" src="https://user-images.githubusercontent.com/7578559/177370304-d5f0e58a-61a8-4e05-b724-73aff3eb72eb.png">
