### ISSUE TITLE
Print out option is not intuitive

### ISSUE THREAD

**Issue by Wehzie** [lakesare/memcode#128]
Hello,

When opening the three-dot context menu and clicking the print out option, then a blank page with the course title is created in most common use scenarios. In order for the print page to display elements laborious steps need to be taken.

In creation mode it always seems to be the case that the print page is blank.
Selecting QA pairs in creation mode doesn't change this behavior.
Personally I would like to see a behavior that shows all cards on the print page when clicking the print option while in creation mode.

It seems that cards need to be manually selected to appear on the print page while in learning mode (there seems to be no select all option). While cards selected as learnt are persistent between sessions, they disappear from the print out page, therefore manually re-selecting each card is necessary for them to appear again. This is very laborious and a changed behavior would be desirable in my opinion.

Thank you :)

**Comment by lakesare** [comment]
Hi!

On the print page we're printing out the flashcards that are ready for review (see the text in white), the behaviour you described is very much expected:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/7578559/136325619-b41307ee-8908-4a70-8ba5-29d34159d4ca.png">

We can add an option to print out either all flashcards, or only the flashcards to review if you'd like.

**Comment by piotrvidal** [comment]
I can take this one @lakesare: so this would be just adding another option to the contextual menu that says 

```
"Print All Out"
"Some description for example: Open a page suitable for printing all cards within this deck."
```

Or some other solution?

**Comment by lakesare** [comment]
@piotrvidal, nice!
Yes, let's make this a separate list item for now, converting it to a modal e.g. will be easy.

**Comment by lakesare** [comment]
Resolved by https://github.com/lakesare/memcode/pull/151, thanks @piotrvidal!

Just deployed it, it's live on Memcode:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/7578559/155662398-86dc7cc8-3086-4aaa-9187-611ed0235131.png">.

As always - don't forget to CMD+SHIFT+R to reset the cache.
