### ISSUE TITLE
exporting of flashcards with images not working

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#13]
If flashcards have images, the export to Excel creates a file successfully. 
But the excel file has errors, and fails in Google Sheets when I try to open it.

**Comment by lakesare** [comment]
I think I should be able to fix this one quickly.
Could you send me an example of your excel file?

**Comment by kgashok** [comment]
[Memcode - CS8251 - Unit 5 - Files (1).xlsx](https://github.com/lakesare/memcode/files/4309750/Memcode.-.CS8251.-.Unit.5.-.Files.1.xlsx)

Here it is.

**Comment by lakesare** [comment]
@kgashok, the file successfully opens in google sheets for me

![image](https://user-images.githubusercontent.com/7578559/76370533-f8c2a880-6358-11ea-8328-9f92543702ce.png)

Are you sure it fails for you?

**Comment by kgashok** [comment]
![image](https://user-images.githubusercontent.com/2399010/76431715-ff443500-63d7-11ea-969b-c73a3591dfb5.png)

**Comment by kgashok** [comment]
I've reported this to Google. I guess this is really a problem they need to look at, anyway.
