### ISSUE TITLE
Import from Excel file happens in reverse order

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#132]
The first row becomes the last flash card in the sequence. 
The last row becomes the first flash card in the sequence.

Even though the "OldestFirst" option is available, it is useful when I want to  further add new flashcards. 
But when in "Learn" mode, the original "reversed" sequence is still maintained.

**Comment by kgashok** [comment]
In addition, there are some changes in the ordering within the sequence as well. For example, Traverse occurs in the 338th position in the Excel file:
![image](https://user-images.githubusercontent.com/2399010/141666579-51ab26ce-f328-4618-a635-ac656eeca57c.png)

and in the Memcode course, it occurs in the 79th position:

![image](https://user-images.githubusercontent.com/2399010/141666668-b12d15c5-43ed-4809-9bb2-2178fdfdf95a.png)

**Comment by lakesare** [comment]
That's serious, will fix!

**Comment by lakesare** [comment]
I can't recreate the ordering reversal (loads in the right order for me), however I see why this might be happening (race condition!).
I deployed the possible fix for you.
In general this needs to be worked on further, we should always assign the explicit position to each flashcard.

**Comment by kgashok** [comment]
[Think Python.xlsx](https://github.com/lakesare/memcode/files/7683605/Think.Python.xlsx)

is the file in question that I am trying to import. Thanks,
