### ISSUE TITLE
Fixed font for inline code (Ctrl-M) and/or block of code (Ctrl-C)

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#137]
I remember the inline code and/or block of code was rendered in **fixed font**, or is it just my imagination? :smile:

Code snippets like the one below is more readable in a fixed font. 
![image](https://user-images.githubusercontent.com/2399010/148584959-e954578b-7412-431c-8f38-e858aacc526c.png)

**Comment by lakesare** [comment]
You're right, it used to be monospace!
Agreed, I'll change it back to monospace later today/tomorrow.

**Comment by kgashok** [comment]
I would love to contribute, if this is simple enough!

**Comment by lakesare** [comment]
Not so simple this time! I added an option for the monospace font, because I prefer the normal font myself.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/7578559/148675035-cfa5f069-1093-4d68-a2c8-6041659784b6.png">

**Comment by kgashok** [comment]
Thanks much!
