### ISSUE TITLE
Option to have courses as alphanumerically sorted list

### ISSUE THREAD

**Issue by andjar** [lakesare/memcode#160]
I really enjoy memcode and have created a number of courses, and to avoid each course growing too large, I have named them with hierarchical names such as `Courses 2022 / Course A / Theme A`. It would be wonderful to be able to have them sorted alphanumerically - and possibly as a list rather than as cards - to make them easier to navigate:

```
Courses 2021 / Course A / Theme A
Courses 2021 / Course B / Theme A
Courses 2022 / Course A / Theme A
Courses 2022 / Course A / Theme B
Courses 2021 / Course A / Theme C
Courses 2022 / Course B / Theme A
Courses 2022 / Course B / Theme B
```

**Comment by lakesare** [comment]
Thank you :-)
I'm working on a very similar functionality right now, and I plan to deploy it to production today.

You would have a dropdown in the header that looks like this:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/7578559/174326971-880f99a3-8cd7-4337-ad84-a497a64e00f3.png">
And you would be able to pin important courses:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/7578559/174327268-cbabdd83-a305-440f-8d7a-d9e8743492ae.png">
And these pinned courses will be sorted alphabetically.

I understand the desire to sort all courses alphabetically (not only the pinned courses) too, I will think of how to do it after I deploy the aforementioned dropdown.

I have such a list of courses myself 😅:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/7578559/174327941-944a4480-93db-46d5-97db-2f9ffc13554c.png">

**Comment by andjar** [comment]
Haha that's perfect! Thank you for the amazing job you are doing!

fre. 17. jun. 2022 kl. 17:21 skrev Evgenia Karunus ***@***.***

**Comment by lakesare** [comment]
Deployed, now everyone can pin some courses, and they will be sorted alphabetically:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/7578559/174412775-084411c6-c19c-4467-a3f7-b01339306844.png">
