### ISSUE TITLE
Korean text disappears after I enter the correct answer in cloze deletion cards

### ISSUE THREAD

**Issue by iopq** [lakesare/memcode#165]
It's actually not there, if I hit enter it marks me wrong

if I input it again it works, so I have to type the answer twice

**Comment by lakesare** [comment]
Do you have this issue too https://github.com/lakesare/memcode/issues/25?

**Comment by iopq** [comment]
no, they just all disappear after I enter the last block, and only if it's the correct answer

**Comment by iopq** [comment]
In the console, I get both `given is wanted` and `given isnt equal to wanted` at the same time

**Comment by lakesare** [comment]
Aha. Could you please give me a link to one of your courses with this issue?

**Comment by iopq** [comment]
https://www.memcode.com/courses/7296

**Comment by iopq** [comment]
If you paste the answer, like just 연락처 into the of the cards it works fine. It's an issue because of how korean syllable blocks are constructed on the fly, and might be in particular a browser/platform issue

**Comment by iopq** [comment]
https://photos.app.goo.gl/AonbhAWwyhT7v5YTA

Recorded using Android with Gboard keyboard

**Comment by lakesare** [comment]
Thank you, could reproduce this! I'll try to fix it today.

**Comment by lakesare** [comment]
Just deployed the possible solution. Please press CMD+SHIFT+R to make sure you get the latest version of code.

Try to:
1. **type in the answer** as you usually do in Korean, and
2. **push the right arrow** on your keyboard.

Please tell me if this works for you.

**Comment by iopq** [comment]
I'm currently using my phone to review, but pressing show answer did the trick! Thanks, fixed for me

**Comment by iopq** [comment]
There's a small bug in the fix:

If the correct word is ABC and I type ABCD it will reset the text field

Example: I changed some of the words to omit the grammatical endings, so the correct answer is shorter

if for the card that has the answer 끄 I write 끄다 it will erase my answer before I can delete the extra jamo. So basically when you exceed the correct answer it will erase it, apparently because it registered the answer as correct already and breaks when you just add random stuff at the end (of course it doesn't know the previous state of the card, so even if you write 끄아 it will mess up too)

**Comment by lakesare** [comment]
🤔
The current solution also makes the review of english words behave unusual on mobile. I'll see what I can do.

**Comment by lakesare** [comment]
I deployed the new solution for Korean inputs.
Works on a desktop for me, please try it on your phone (make sure to hard reload the application).

**Comment by iopq** [comment]
Works great on both now, thanks
