### ISSUE TITLE
Not clear how to add cards to a course when I have cards due

### ISSUE THREAD

**Issue by iopq** [lakesare/memcode#166]
I usually just click the course and get to add, but I have no idea what to do when cards are due, but I actually want to change the cards. There seems not to be any special URL for it either

**Comment by lakesare** [comment]
You can click on the course, and then click on the title of the course:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/7578559/185673870-a1d2e84f-9946-46c9-95e5-fed574c53414.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/7578559/185673916-49cbcff8-13bc-4c65-bbad-c58498c43694.png">

**Comment by iopq** [comment]
No dice, it wants me to review

![Uploading Screenshot from 2022-08-21 18-24-07.png…]()

**Comment by lakesare** [comment]
But try clicking on "Quick Korean" once you're on this review page!

**Comment by lakesare** [comment]
No way! Does it go to the /courses/:id page when you click here at all?

<img width="219" alt="image" src="https://user-images.githubusercontent.com/7578559/185940437-5d999fe2-f9fe-491e-b763-739e9466c45a.png">

**Comment by iopq** [comment]
> No way! Does it go to the /courses/:id page when you click here at all?
> 
> <img alt="image" width="219" src="https://user-images.githubusercontent.com/7578559/185940437-5d999fe2-f9fe-491e-b763-739e9466c45a.png">

all of the links point to /courses/:id/review when you have cards due

**Comment by lakesare** [comment]
Would be helpful if you can record the video with this issue too (so that it's visible where you click), I can't think of what could cause the title to lead to `/courses/:id/review` right now.

**Comment by iopq** [comment]
https://photos.app.goo.gl/u8huij4973Dd4c2c8

It went directly to my profile, but since I didn't want to show my email in the video, I went to contact us page to start it

**Comment by lakesare** [comment]
I think you only pressed on the link in the header dropdown, no?

<img width="391" alt="image" src="https://user-images.githubusercontent.com/7578559/188946583-bb4404fc-a4a8-4dd6-90d0-9d0978eaa215.png">

You're supposed to click on the course title:

<img width="204" alt="image" src="https://user-images.githubusercontent.com/7578559/188946622-bce3a488-690e-46bc-91b9-30958872d4e0.png">

___

If you want to access /courses/:id right away from the dropdown, consider pinning your course:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/7578559/188946802-9d71506b-13d5-4042-be93-f3aa957dd887.png">

**Comment by iopq** [comment]
The pinned course workaround works

https://photos.app.goo.gl/9BmV4bqGmTagBJRF7

But the similar looking link below it doesn't work the same

**Comment by lakesare** [comment]
That's normal! You can always click on the link below, and THEN click on the course title on the newly opened page.
This is done so because it's more pleasant/easier to click on the entire row (on desktop certainly). Might be a dubious solution, will see!
