### ISSUE TITLE
Multiple authors for a course

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#17]
Can a course have multiple authors, allowing for collaboration.
I am encouraging students to collaborate and produce flashcards as a team of 4-10.

**Comment by lakesare** [comment]
This sounds like a great idea! I'll see what can be done.

**Comment by lakesare** [comment]
@kgashok, I'd really appreciate a github star btw, - memcode could benefit from some stars :-)

**Comment by lakesare** [comment]
Done ✅ 

![image](https://user-images.githubusercontent.com/7578559/77195391-5f875500-6b03-11ea-859c-6ec85817698c.png)
![image](https://user-images.githubusercontent.com/7578559/77195430-6dd57100-6b03-11ea-90c9-ead134b2d886.png)

Users can invite coauthors now. Coauthors will be notified (but won't be emailed).

**Comment by kgashok** [comment]
Wow! Thank you very much!
