### ISSUE TITLE
Decks inaccessible after learning stopped. 

### ISSUE THREAD

**Issue by gs221** [lakesare/memcode#185]
I have found that I can no longer access decks after I have stopped learning them; they no longer appear in the list of courses. 

For example, you can see below that the pie chart shows I have created 17 courses...

![image](https://user-images.githubusercontent.com/47386535/212500124-1830ddb4-b415-4d41-b414-0305ec25039f.png)

Yet none are shown in the course area, where they would be if they were being learned. 

![image](https://user-images.githubusercontent.com/47386535/212500134-152c2e41-15e0-47f4-a11a-a17641a94aca.png)

**Comment by lakesare** [comment]
Interesting, can't immediately see what's going on looking through the source code.  
Are you 1. signed in 2. are the courses public?

**Comment by gs221** [comment]
Hello, 

I am signed in, and all but one course is private. It seems to affect both public and private decks.

**Comment by lakesare** [comment]
Ok could reproduce the issue, working on it.

**Comment by lakesare** [comment]
Fixed it, please try to access your profile page again, and tell me if it worked for you.

**Comment by gs221** [comment]
Yes! that's it working now, thank you very much!

**Comment by lakesare** [comment]
Nice, thanks for reporting!
