### ISSUE TITLE
Login with Github on Gitpod

### ISSUE THREAD

**Issue by pegak** [lakesare/memcode#186]
Hi,
I tried to run the Memcode in Gitpod, but I wasn't able to start it, so I tried it my own Github OAUTH and when I try to login I get this error:
`"insert into \"course_user_is_learning\" (\"active\", \"course_id\", \"user_id\") values ($1, $2, $3) - insert or update on table \"course_user_is_learning\" violates foreign key constraint \"course_user_is_learning_course_id_fkey\""`.

**Comment by pegak** [comment]
Nevermind, I just restarted DB and it started to work, don't know why. :)

**Comment by lakesare** [comment]
Uh good to know!
