### ISSUE TITLE
Regression: I no longer have any button that takes me to edit the course on desktop

### ISSUE THREAD

**Issue by iopq** [lakesare/memcode#187]
![image](https://user-images.githubusercontent.com/1817528/213626419-55738427-14b9-4a9c-901c-c00adfc1e30a.png)

Expected: I should have a link to https://www.memcode.com/courses/7296/
Result: I only have two links to https://www.memcode.com/courses/7296/review so I can't edit the course without manually editing the URL

it used to be that pinning the course gave me the link I wanted

**Comment by lakesare** [comment]
You can access the course editing page by clicking here.
<img width="189" alt="image" src="https://user-images.githubusercontent.com/7578559/213645801-07b6db3a-ab4d-4216-b052-37588ab71789.png">

**Comment by iopq** [comment]
Thanks, that works, but it requires two clicks from the front page. Any idea to make it more convenient?

**Comment by lakesare** [comment]
Uh I think you're right, it's a regression, we had both the `#view` and `#review`/`#learn` access previously (I changed it in order to have `18 hours`-before-next-review label for pinned courses, too).  
I'll make it so that previous behaviour is restored but we also get the `18 hours`-before-next-review label & hit you up, thanks for drawing my attention to this.

**Comment by iopq** [comment]
Thanks, it's resolved for me

**Comment by lakesare** [comment]
It's not, I didn't push anything yet, you just used some other device that has the old version of a site cached.

**Comment by iopq** [comment]
Haha, you're right. Have you considered cache busting when you deploy? I used to do it with file names, but maybe there's an easier way

**Comment by lakesare** [comment]
I'd really like to have cache busting, in fact it causes outages for people when I change the backend and their frontend cache is yet to refresh.
We use service workers for caching however, so it's not super obvious how to do it (I spent a few hours on this).

**Comment by lakesare** [comment]
@iopq, now this is fixed!
