### ISSUE TITLE
Flashcards moved from course to course should retain learning progress.

### ISSUE THREAD

**Issue by lakesare** [lakesare/memcode#35]
![image](https://user-images.githubusercontent.com/7578559/77588232-49b2cf00-6f0b-11ea-911e-36453c3b5e9c.png)

Right now, when we move the flashcard to another course, - all of our progress with that flashcard disappears. Make sure it stays.

**Comment by pavikishoor** [comment]
Ms.Mythili and me are working on this issue. It will be helpful, if u give much more details on "" all of our progress with that flashcard disappears "". So that we can understand issue in detail. We are not clear whether the problem is with Flashcard disappearing or with progress disappearing.

**Comment by pavikishoor** [comment]
Hi Evgenia,

This is Mythili(Faculty) and Pavithrayani( student- III IT) from KGiSL.

Both are working on issue number #35(Flashcards moved from course to course should retain learning progress). It will be helpful if u give a little more clarification with screenshots.
We have doubt, need to give a solution for disappearing Flashcards from an existing course or for disappearing learning progress  (learn and ignore button).

Thanks

**Comment by lakesare** [comment]
Hi, @pavikishoor! This issue refers to the 'Move N flashcard to ...' functionality.

![image](https://user-images.githubusercontent.com/7578559/78450347-61225280-7697-11ea-836c-7389d60c4144.png)

While you're working on it, - please disable autocomplete for that input.

Imagine we already learned and reviewed the flashcard we're moving.
After it's moved to the new course, - our progress gets deleted. 
We want to clone progress from one problem_user_is_learning to another one.

**Comment by pavikishoor** [comment]
@lakesare ! To whichever course the flashcard is moved. Each flashcard should retain whether it is learned or not, Reviewed or not and also the rating given to that particular flashcard.
Whether my understanding on this issue is correct?

**Comment by lakesare** [comment]
Yep :-) For the users that are already learning both courses though.
