### ISSUE TITLE
New FlashCard creation pane can be located at the top

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#40]
This appears now at the bottom of all the existing cards. 
So to add a new card, the user has to scroll all the way to the end of all cards. 

Several times I have wished that this addition dialog could be available at the very top.

**Comment by lakesare** [comment]
I considered that, however then the flashcard order would be reversed. I believe the flashcards we create the first should remain on the top of the page.

**Comment by lakesare** [comment]
Made flashcard-button-at-the-top the default option, merged!
