### ISSUE TITLE
"Test Drive" fails to launch a review a 2nd time around

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#66]
When the `Test Drive` button is clicked, it launches a review alright. 
But if you click `Test Drive` button immediately thereafter, there is no response.

**Comment by lakesare** [comment]
That's cause it's a link, and we're already on the right page.
Interesting that you expected it to launch the review anew 🤔
We could add the 'redux.refreshState()' handler (this is pseudocode) to that link, but not sure if people use it this way.

**Comment by kgashok** [comment]
I was in a testing mode to find a better way to fix the "ProgressBar". 
So I was "test driving" the same course back to back. That's the "use case"! 

I was also hoping this would be a easy issue fix - but seems that is not the case.
I understand if you just want to close this issue. Thanks,
