### ISSUE TITLE
Export to CSV - the order of flashcard information

### ISSUE THREAD

**Issue by kgashok** [lakesare/memcode#72]
It seems to be in order of creation of flashcards. 
It must be in the order as listed in the course.

The attached file is the CSV generated for course https://www.memcode.com/courses/2288. 

[Memcode - CS_8151 - Unit 2 - Data, Expressions and Statements.xlsx](https://github.com/lakesare/memcode/files/4429781/Memcode.-.CS_8151.-.Unit.2.-.Data.Expressions.and.Statements.xlsx)

**Comment by anandvenkat4** [comment]
@lakesare Should we order by position?

**Comment by lakesare** [comment]
@anandvenkat4, yes, by the `problem.position` field.

**Comment by eyssette** [comment]
The fix doesn't seem to work.

Course : https://www.memcode.com/courses/4369
Export : [Memcode - Philosophie _ les méthodes – Révisions 2020-2021.xlsx](https://github.com/lakesare/memcode/files/6684644/Memcode.-.Philosophie._.les.methodes.Revisions.2020-2021.xlsx)

Thanks for your wonderful app!

**Comment by lakesare** [comment]
Indeed, thanks for reporting! I'll look into this today/tomorrow and get back to you.

**Comment by lakesare** [comment]
@eyssette, fixed this!
You can try again, and feel free to get back to me if this doesn't work (remember to refresh your cache with CMD+SHIFT+R).

**Comment by eyssette** [comment]
> @eyssette, fixed this!
> You can try again, and feel free to get back to me if this doesn't work (remember to refresh your cache with CMD+SHIFT+R).

It works! Thank you!
