### ISSUE TITLE
'Move to' contains same course.

### ISSUE THREAD

**Issue by CoderToCode** [lakesare/memcode#75]
While moving the card from one course to another, the option contains the same course name.

![image](https://user-images.githubusercontent.com/42794423/78845760-23bb1d80-7a27-11ea-8d64-5a4a56c3f59a.png)
Eg; When I  move a card from `CS_8251 - Unit 2 - Selection Sort`, the dropdown shows the same course `CS_8251 - Unit 2 - Selection Sort` to move.

**Comment by lakesare** [comment]
Good catch, Sagar.
We have a similar issue in the Invite Coauthors input (already-added users can be selected).

**Comment by daniel-eder** [comment]
It seems the new "export" (= move cards to) functionality already implements this, in a quick test I cannot see the current course when moving: 
![image](https://user-images.githubusercontent.com/1525711/94411762-3cf08b80-0179-11eb-91c0-c466f8fa7679.png)

**Comment by lakesare** [comment]
Neat, closing the issue ✅
