### ISSUE TITLE
Allow interactive cards for programming with tests

### ISSUE THREAD

**Issue by dit7ya** [lakesare/memcode#86]
It would be great to learn programming where you type the answers which runs some actual code and passes tests. Something like https://www.executeprogram.com/.

**Comment by lakesare** [comment]
Hi @dit7ya, thanks for suggestion!

Running the interpreter would only be useful for beginner flashcards in Js/CSS/etc.
Once you're on the more advanced level, you'd be more likely:
- to want to import the library,
- to want the answer more abstract than a simple number/string answer (see https://www.memcode.com/courses/2128 e.g.)

So this kind of functionality is awesome, but only helpful at the initial stage of learning a language, and it's better done with pre-created courses (like on www.executeprogram.com) as opposed to primarily user-created courses (like on www.memcode.com).
