### ISSUE TITLE
Suggestion: Default rating of 1 in review

### ISSUE THREAD

**Issue by daniel-eder** [lakesare/memcode#93]
Currently cards are by default rated 5/5 in review, that means if one accidentally clicks next (happens easily on mobile) they might not see the card again for a long time. As there is currently no review page where one can edit the card ratings, that card is basically gone at that point.

Suggestion: Instead rate cards with 1 by default. If one clicks next the card will automatically show up in the next review and can be rated correctly.

**Comment by lakesare** [comment]
In most cases the answer is rated at 5 (if not initially - then in the long term). Making it 1 by default would require too many clicks per each flashcard.

I see the issue you're describing though. One way to 'reset' the flashcard is to go to the `/courses/:id/learn` page, then to click 'Learn Flashcards', and then to click 'ignore'&'learn' on the desired flashcard.
Certainly not ideal, and I think it would be nice to have an ability to 'Reset Progress' in the 'see more actions' dropdown, e.g. upon clicking the 'MORE' button
![image](https://user-images.githubusercontent.com/7578559/88582700-93055d80-d068-11ea-8b68-33710b396c24.png)

**Comment by daniel-eder** [comment]
The workaround is a good solution, it removes the immediate need for a reset feature. Thank you!
